import type { AuthoredLesson } from "../types";
import { returnsLessons } from "./manifest";

export const compoundingAndCumulativeReturnsLesson: AuthoredLesson = {
  id: returnsLessons[2].id,
  moduleSlug: "returns",
  slug: returnsLessons[2].slug,
  title: returnsLessons[2].title,
  eyebrow: "Výnosy a složené zhodnocení",
  position: 3,
  estimatedMinutes: returnsLessons[2].estimatedMinutes,
  sections: [
    { id: "why-addition-fails", label: "Proč sčítání výnosů nefunguje" },
    { id: "growth-factors", label: "Růstové faktory" },
    { id: "explore", label: "Prozkoumej složené zhodnocení" },
    { id: "asymmetry", label: "Asymetrie ztráty" },
    { id: "practice", label: "Procvičení" },
  ],
  navigation: { previous: { href: "/learn/returns/simple-returns", label: "Jednoduché výnosy" } },
  blocks: [
    { id: "why-addition-fails", type: "heading", title: "V jednotlivých obdobích se výnosy násobí, ne jednoduše sčítají.", body: "Každé období mění hodnotu, od které začíná další období. Právě proto se posloupnost výnosů počítá násobením." },
    { id: "recap", type: "paragraph", content: "V lekci 2 jsme každé období posuzovali zvlášť. Teď je otázka jiná: jaký je po několika obdobích celkový výsledek a konečná hodnota?" },
    { id: "prediction", type: "multipleChoiceQuestion", prompt: "Než výpočet odhalíš, předpověz výsledek. Počáteční kapitál je 10 000. V 1. období vydělá 20 % a ve 2. období ztratí 20 %. Jaký bude konečný kapitál?", options: [{ id: "a", label: "10 000, protože +20 % a −20 % se vyruší." }, { id: "b", label: "9 600." }, { id: "c", label: "8 000." }], correctOptionId: "b", correctExplanation: "Po zisku se 10 000 změní na 12 000. Ztráta 20 % se pak počítá z 12 000, ne z 10 000: 12 000 × 0,80 = 9 600.", incorrectExplanation: "Druhé procento používá nový základ. Nejprve: 10 000 × 1,20 = 12 000. Potom: 12 000 × 0,80 = 9 600. Sčítání +20 % a −20 % změnu základu přehlíží." },
    { id: "twenty-example", type: "workedExample", title: "+20 % následovaných −20 %", introduction: "Použij 10 000 jako počáteční hodnotu a každé období aplikuj v pořadí.", steps: [{ label: "Počáteční hodnota", value: "10 000" }, { label: "Po +20 %", value: "12 000", emphasis: true }, { label: "Po −20 %", value: "9 600", emphasis: true }, { label: "Kumulativní výnos", value: "−4 %", emphasis: true }], conclusion: "Aritmetický součet je 0 %, ale skutečný kumulativní výnos je −4 %. Ztráta se počítala z vyšší hodnoty 12 000." },
    { id: "growth-factors", type: "heading", title: "Po přičtení jedničky se výnos stane růstovým faktorem.", body: "Růstové faktory názorně ukazují násobení. Uvnitř výpočtů používají desetinné výnosy." },
    { id: "growth-callout", type: "conceptCallout", title: "Tři způsoby zápisu stejného pohybu", content: "+5 % je zobrazené procento, 0,05 je desetinný výnos používaný ve výpočtech a 1,05 je růstový faktor. Stejně tak −12 % je −0,12 a jeho růstový faktor je 0,88." },
    { id: "cumulative-formula", type: "formula", expression: "R_cumulative = Π(1 + R_t) − 1", latex: String.raw`R_{\mathrm{cumulative}} = \prod_{t=1}^{n}(1+R_t)-1`, variables: [{ symbol: "R_cumulative", description: "celkový výnos za všechna období" }, { symbol: "R_t", description: "výnos v jednotlivém období" }, { symbol: "Π", description: "vynásobení všech růstových faktorů" }] },
    { id: "value-formula", type: "formula", expression: "V_n = V_0 × Π(1 + R_t)", latex: String.raw`V_n = V_0 \times \prod_{t=1}^{n}(1+R_t)`, variables: [{ symbol: "V_0", description: "počáteční hodnota investice" }, { symbol: "V_n", description: "konečná hodnota po n obdobích" }, { symbol: "R_t", description: "výnos každého období" }] },
    { id: "explore", type: "heading", title: "Sleduj hodnotu v každém období.", body: "Průzkumník zobrazuje vedle složeného výsledku i aritmetický součet, aby byl rozdíl jasný." },
    { id: "compounding-explorer", type: "interactiveFigure", figure: "compounding-explorer", title: "Průzkumník složeného zhodnocení", description: "Začni posloupností +20 %, −20 % a potom ji uprav. Každý řádek ukazuje hodnotu, která se stane základem dalšího období." },
    { id: "two-gains", type: "numericQuestion", prompt: "Dva po sobě jdoucí výnosy jsou +10 % a +10 %. Jaký je kumulativní výnos?", answer: 21, tolerance: 0.05, unit: "%", correctExplanation: "Růstové faktory jsou 1,10 a 1,10. Jejich součin je 1,21, takže kumulativní výnos je 0,21 = 21 %, ne 20 %.", incorrectExplanation: "Růstové faktory násob, výnosy nesčítej: (1 + 0,10)(1 + 0,10) − 1 = 0,21 = 21 %." },
    { id: "price-series", type: "heading", title: "Časová řada ceny a složené výnosy si odpovídají.", body: "Bez externích peněžních toků můžeš celkový výnos vypočítat přímo z první a poslední ceny." },
    { id: "price-series-example", type: "workedExample", title: "100 → 110 → 99", steps: [{ label: "Výnos za 1. období", value: "+10 %" }, { label: "Výnos za 2. období", value: "−10 %" }, { label: "Složený výnos", value: "1,10 × 0,90 − 1 = −1 %", emphasis: true }, { label: "Přímý cenový výnos", value: "99 ÷ 100 − 1 = −1 %", emphasis: true }], conclusion: "Obě metody dávají stejný výsledek, protože součin po sobě jdoucích poměrů cen se zjednoduší na konečnou cenu dělenou počáteční cenou." },
    { id: "multi-period", type: "multiNumericQuestion", prompt: "Pro řadu 100 → 110 → 99 vypočítej první výnos, druhý výnos a kumulativní výnos.", answers: [{ id: "first", label: "100 → 110", answer: 10, tolerance: 0.05, unit: "%" }, { id: "second", label: "110 → 99", answer: -10, tolerance: 0.05, unit: "%" }, { id: "cumulative", label: "Kumulativní výnos", answer: -1, tolerance: 0.05, unit: "%" }], correctExplanation: "Výnosy za období jsou +10 % a −10 %. Jejich růstové faktory jsou 1,10 a 0,90, takže kumulativní výnos je 1,10 × 0,90 − 1 = −1 %.", incorrectExplanation: "Každé období vypočítej z jeho vlastní předchozí ceny a potom vynásob růstové faktory. +10 % a −10 % nesčítej." },
    { id: "asymmetry", type: "heading", title: "Ke smazání ztráty potřebuješ větší zisk.", body: "Ztráta zmenší základ. Návrat k původní hodnotě proto vyžaduje zisk vypočtený z menšího čísla." },
    { id: "recovery-explorer", type: "interactiveFigure", figure: "recovery-explorer", title: "Potřebné zotavení po ztrátě", description: "Vyzkoušej velikost ztráty. Potřebný zisk pro zotavení vychází z 1 ÷ (1 − ztráta) − 1." },
    { id: "loss-practice", type: "numericQuestion", prompt: "Investice klesne o 50 %. Jaký výnos je od nové hodnoty potřeba k návratu na původní hodnotu?", answer: 100, tolerance: 0.05, unit: "%", correctExplanation: "Po ztrátě 50 % se ze 100 stane 50. K návratu na 100 je potřeba zisk 50 ze základu 50: 50 ÷ 50 = 100 %.", incorrectExplanation: "Ztráta 50 % hodnotu rozpůlí. Zotavení začíná z této poloviční hodnoty, takže je potřeba ji zdvojnásobit: +100 %." },
    { id: "concept", type: "multipleChoiceQuestion", prompt: "Proč se jednoduché výnosy za jednotlivá období obvykle nedají sečíst pro výpočet kumulativního výsledku?", options: [{ id: "a", label: "Protože výnos každého období se počítá z hodnoty vytvořené předchozími obdobími." }, { id: "b", label: "Protože procenta se ve financích nikdy nedají sčítat." }, { id: "c", label: "Protože kumulativní výnos se vždy rovná konečné změně ceny v korunách." }], correctOptionId: "a", correctExplanation: "Každý výnos působí na měnící se základ. Násobení růstových faktorů tuto posloupnost zachytí, zatímco prosté sčítání obvykle ne.", incorrectExplanation: "Problémem je měnící se základní hodnota. Výnosy někdy lze sečíst jako aproximaci, ale přesný kumulativní výsledek vzniká složením růstových faktorů." },
    { id: "takeaway", type: "takeaway", title: "Shrnutí", content: "Výnos za období popisuje jeden interval. Kumulativní výnos popisuje celou posloupnost. K jeho výpočtu a výpočtu konečné hodnoty násob růstové faktory; výnosy za období nesčítej." },
    { id: "checkpoint", type: "checkpoint", label: "Než budeš pokračovat", content: "Teď umíš rozlišit výnos za období, kumulativní výnos a konečnou hodnotu, složit posloupnost pomocí růstových faktorů a vysvětlit, proč se stejně velké procentní zisky a ztráty nevyruší." },
  ],
};
