import type { AuthoredLesson, LessonBlock } from "../types";
import { foundationsLessons } from "./manifest";

type StepKind = "lesson" | "mastery";
type AuthoredStep = { title: string; kind?: StepKind; blocks: LessonBlock[] };

const paragraph = (id: string, content: string): LessonBlock => ({ id, type: "paragraph", content });
const concept = (id: string, title: string, content: string): LessonBlock => ({ id, type: "conceptCallout", title, content });
const question = (id: string, prompt: string, options: string[], correct: number, correctExplanation: string, incorrectExplanation = correctExplanation): LessonBlock => ({ id, type: "multipleChoiceQuestion", prompt, options: options.map((label, index) => ({ id: String(index), label })), correctOptionId: String(correct), correctExplanation, incorrectExplanation });
const numeric = (id: string, prompt: string, answer: number, unit: string, correctExplanation: string, incorrectExplanation = correctExplanation): LessonBlock => ({ id, type: "numericQuestion", prompt, answer, tolerance: 0.000001, unit, correctExplanation, incorrectExplanation });
const figure = (id: string, kind: Extract<LessonBlock, { type: "interactiveFigure" }>["figure"], title: string, description: string): LessonBlock => ({ id, type: "interactiveFigure", figure: kind, title, description });
const mastery = (title: string, block: LessonBlock): AuthoredStep => ({ title, kind: "mastery", blocks: [block] });
const bridge = (content: string): LessonBlock => ({ id: "lab-bridge", type: "labBridge", title: "Kde to využiješ", content });
const summary = (content: string): LessonBlock => ({ id: "summary", type: "lessonSummary", title: "Shrnutí lekce", content });

const whyInvest: AuthoredStep[] = [
  { title: "Nejdřív vyber nástroj, až potom řeš výnos", blocks: [question("opening", "Peníze budeš potřebovat za tři měsíce. Co je nejdůležitější?", ["Snadný přístup a stabilita", "Co nejvyšší dlouhodobý růst", "Vlastnit co nejvíc různých investic"], 0, "Peníze na blízký výdaj mají být hlavně dostupné a stabilní. Hodnota investice může klesnout právě ve chvíli, kdy ji potřebuješ.", "Krátký horizont nedává moc času na zotavení z poklesu trhu. Začni tím, kdy budeš peníze potřebovat, ne nejvyšším možným výnosem.")] },
  { title: "Spoření a investování řeší jiné potřeby", blocks: [paragraph("tools", "Spoření drží peníze snadno dostupné a nominálně poměrně stabilní. Při investování je vkládáš do aktiv, jejichž hodnota může růst i klesat, s cílem dosáhnout budoucího růstu nebo příjmu."), concept("uncertainty", "Růst lze očekávat, ne zaručit", "Dlouhý horizont dává nejistým výsledkům více času, ale zisk nezaručí. Peníze na příští nájem mají jiný úkol než peníze, které nebudeš potřebovat 15 let.")] },
  { title: "Porovnej dva časové horizonty", blocks: [figure("horizon", "time-horizon-explorer", "Kdy budeš peníze potřebovat?", "Porovnej blízký výdaj s penězi určenými na vzdálenější budoucnost. Jde o princip plánování, ne o osobní investiční doporučení.")] },
  { title: "Kupní síla se může měnit", blocks: [{ id: "inflation-example", type: "workedExample", title: "Částka se nezměnila, nákup zdražil", steps: [{ label: "Hotovost", value: "1 000 Kč" }, { label: "Stejný nákup po zdražení", value: "1 050 Kč" }], conclusion: "Na účtu je stále 1 000 Kč, ale stejný nákup už za ně nepořídíš. Hotovost má nízké kolísání nominální hodnoty, přesto čelí riziku ztráty kupní síly." }] },
  mastery("Ověření znalostí · krátký horizont", question("mastery-horizon", "Jak nejlépe popsat peníze na nájem splatný za tři měsíce?", ["Dlouhodobý kapitál, který může přijmout nejistotu trhu", "Peníze na blízký výdaj, u kterých je důležitá likvidita a stabilita", "Peníze, jejichž kupní síla se nemůže změnit"], 1, "U známého blízkého výdaje jsou likvidita a stabilita obzvlášť důležité.", "Nájem je blízký závazek. Pokles trhu před splatností by mohl způsobit, že potřebná částka nebude včas k dispozici.")),
  mastery("Ověření znalostí · dlouhý horizont", question("mastery-guarantee", "Co mění horizont 15 let?", ["Zaručuje kladný investiční výnos", "Odstraňuje inflační riziko", "Dává nejistému výsledku více času, ale zisk nezaručuje"], 2, "Více času může usnadnit zvládání výkyvů a umožnit složené zhodnocení. Ztráta je však stále možná.", "Čas mění podmínky, ne záruku. Investice může prodělat i během dlouhého období.")),
  { title: "Použij každý nástroj pro správný účel", blocks: [bridge("V Portfolio Labu uvidíš hotovost vedle investic. Snadno tak rozlišíš dostupné peníze od kapitálu vystaveného pohybu cen."), summary("Spoření dává přednost dostupnosti a nominální stabilitě. Investování přijímá nejistotu výměnou za možnost budoucího růstu nebo příjmu. Časový horizont a inflace vysvětlují, proč tyto nástroje nejsou zaměnitelné.")] },
];

const stocks: AuthoredStep[] = [
  { title: "Začni vlastnictvím", blocks: [question("opening", "Co představuje jedna akcie?", ["Půjčku, kterou musí firma splatit", "Vlastnický podíl ve firmě", "Zaručený nárok na budoucí zisk"], 1, "Akcie představuje vlastnický podíl. Její cena i případná dividenda se mohou měnit a výnos není zaručen.", "Dluhopis je půjčka emitentovi. Akcie znamená vlastnictví, ale nezaručuje zisk ani drobnému akcionáři nedává každodenní kontrolu nad firmou.")] },
  { title: "Počet akcií mění cenu v hodnotu pozice", blocks: [{ id: "position-formula", type: "formula", expression: "positionValue = quantity × marketPrice", latex: "V = q \\times P", variables: [{ symbol: "q", description: "Počet vlastněných akcií" }, { symbol: "P", description: "Aktuální tržní cena jedné akcie" }, { symbol: "V", description: "Aktuální hodnota pozice" }] }, numeric("position-practice", "Vlastníš 3 akcie po 150 Kč. Jakou hodnotu má pozice?", 450, "Kč", "3 × 150 Kč = 450 Kč. Hodnotu pozice určuje počet akcií a cena jedné akcie.", "Vynásob 3 akcie tržní cenou 150 Kč za kus.")] },
  { title: "Sleduj, jak cena mění hodnotu pozice", blocks: [figure("position", "stock-position-explorer", "Hodnota akciové pozice", "Změň počet akcií nebo tržní cenu. Nejdřív výsledek odhadni, potom ho porovnej s výpočtem počet × cena.")] },
  { title: "Tržní cena není vnitřní hodnota", blocks: [concept("price-value", "Tržní cena je pozorovaná cena obchodu", "Ukazuje, za kolik jsou účastníci trhu právě ochotni směnit jednu akcii. Není automaticky skutečnou či vnitřní hodnotou firmy. Nízká cena jedné akcie také sama o sobě neznamená, že je firma levná.")] },
  mastery("Ověření znalostí · přepočet pozice", numeric("mastery-position", "Stále vlastníš 3 akcie, ale cena klesla na 120 Kč. Jaká je nová hodnota pozice?", 360, "Kč", "3 × 120 Kč = 360 Kč. Počet akcií se nezměnil, nižší cena snížila hodnotu pozice.", "Ponech počet 3 a vynásob ho novou cenou 120 Kč.")),
  mastery("Ověření znalostí · cena a hodnota", question("mastery-intrinsic", "Akcie se obchoduje za 75 Kč. Co z toho samotného můžeš vyvodit?", ["Jedna akcie se právě obchoduje za 75 Kč", "Celá firma má hodnotu 75 Kč", "Akcie je podhodnocená"], 0, "Kotace udává cenu jedné akcie. Pro hodnotu firmy nebo odhad vnitřní hodnoty potřebuješ další informace.", "Cena jedné akcie sama neříká, jakou hodnotu má celá firma ani zda je akcie podhodnocená.")),
  { title: "Čti pozici jako počet × cena", blocks: [bridge("Tuhle znalost využiješ při čtení pozic v Portfolio Labu: uvidíš počet, tržní cenu i celkovou hodnotu pozice."), summary("Akcie je vlastnický podíl. Aktuální hodnota pozice se rovná počtu akcií × tržní cena a s cenou se mění. Tržní cenu lze pozorovat, vnitřní hodnota je odhad a není totéž.")] },
];

const etfs: AuthoredStep[] = [
  { title: "Ukazatel, nebo fond?", blocks: [question("opening", "Co může investor koupit na burze?", ["Samotný index", "Podíly ETF"], 1, "ETF je fond a cenný papír s obchodovatelnými podíly. Index je pravidly definovaný ukazatel určitého koše aktiv.", "Index koš popisuje a měří. Investovat lze do podílů ETF, které se ho může snažit sledovat.")] },
  { title: "Odděl index od ETF", blocks: [figure("map", "index-etf-visual", "Od pravidel k fondu, který můžeš vlastnit", "Index určuje koš a jeho váhy. ETF se ho může snažit sledovat držením konkrétních investic. Vlastníš podíly fondu, ne samotný index.")] },
  { title: "Podívej se pod název fondu", blocks: [figure("holdings", "etf-holdings-visual", "Zjednodušený ETF se čtyřmi částmi", "Firma A tvoří 45 %, B 30 %, C 15 % a všechny ostatní pozice dohromady 10 %. Samotný počet názvů neukazuje, jak vyvážené expozice jsou.")] },
  { title: "Mnoho pozic může být stále koncentrovaných", blocks: [question("concentration", "ETF vlastní mnoho firem, ale dvě největší pozice tvoří 75 %. Je automaticky dobře diverzifikované?", ["Ano, protože obsahuje mnoho názvů firem", "Ne, největší váhy mohou stále ovládat výsledek", "Ano, protože každé ETF má stejné váhy"], 1, "Počet pozic je jen jedna informace. O jejich vlivu rozhodují váhy a společná rizika.", "Dvě největší pozice tvoří tři čtvrtiny fondu. Mnoho malých pozic tuto koncentraci nevyruší.")] },
  mastery("Ověření znalostí · investiční nástroj", question("mastery-vehicle", "Které tvrzení je správné?", ["ETF a jeho index jsou tentýž cenný papír", "Do indexu lze vždy přímo investovat", "ETF může sledovat index, ale fond a ukazatel jsou dvě různé věci"], 2, "ETF je investovatelný fond, zatímco index je ukazatel nebo soubor pravidel.", "Vztah sledování je propojuje, ale nedělá z nich stejný objekt.")),
  mastery("Ověření znalostí · váhy", question("mastery-weights", "Firma A má v ETF váhu 45 %. Co to znamená?", ["Má na výsledek ETF větší vliv než pozice s vahou 5 %", "ETF zaručuje výnos 45 %", "Investor přímo vlastní 45 % firmy A"], 0, "Větší váha dává dané pozici větší vliv na výsledek fondu.", "Váha popisuje podíl pozice ve fondu. Neslibuje výnos ani neznamená přímé vlastnictví firmy investorem.")),
  { title: "Zkoumej obsah, ne jen název", blocks: [bridge("Na stránce ETF pak uvidíš jeho největší pozice a sektorové i geografické zastoupení. Snáze tak odhalíš skutečné expozice a koncentraci."), summary("Index měří koš sestavený podle pravidel. ETF je obchodovatelný fond, který může index sledovat. Pozice a jejich váhy odhalují expozice; mnoho pozic samo o sobě nezaručuje dobrou diverzifikaci.")] },
];

const bondsAndCash: AuthoredStep[] = [
  { title: "Hotovost má v portfoliu svůj úkol", blocks: [question("opening", "Která vlastnost nejlépe vystihuje hotovost?", ["Vysoká likvidita a malé kolísání nominální hodnoty", "Zaručený růst kupní síly", "Vlastnictví firmy"], 0, "Hotovost je užitečná díky dostupnosti a nominální stabilitě. Inflace ale může snížit, co za ni koupíš.", "Hotovost není podíl ve firmě a nezaručuje kupní sílu. Její hlavní výhodou je dostupnost a nominální stabilita.")] },
  { title: "Vlastnit, půjčovat a držet hotovost", blocks: [figure("roles", "asset-comparison", "Tři odlišné vztahy", "Porovnej hotovost, dluhopis a akcii. Každý nástroj může mít jinou roli a nese jiný druh rizika.")] },
  { title: "Dluhopis představuje půjčku", blocks: [paragraph("bond", "Koupí dluhopisu půjčuješ peníze jeho emitentovi. Jistina je částka splatná při splatnosti, kupón je sjednaná úroková platba. Platby závisejí na tom, zda emitent své závazky splní."), { id: "bond-terms", type: "workedExample", title: "Dluhopis 1 000 Kč s ročním kupónem 5 %", steps: [{ label: "Jistina", value: "1 000 Kč" }, { label: "Roční kupón", value: "50 Kč" }, { label: "Splatnost", value: "Datum vrácení jistiny" }], conclusion: "Kupón je 1 000 Kč × 5 % = 50 Kč ročně. Emitent může selhat a tržní cena dluhopisu se může před splatností měnit." }] },
  { title: "Proč se cena staršího dluhopisu mění", blocks: [concept("rates", "Nové alternativy mění atraktivitu", "Když nové srovnatelné dluhopisy nabízejí vyšší sazby, starší dluhopis s nižší pevnou platbou je při stejné ceně méně lákavý. Jeho tržní cena může klesnout, aby byl pro kupující konkurenceschopnější.")] },
  mastery("Ověření znalostí · vztah k emitentovi", question("mastery-lending", "Co především děláš, když koupíš firemní dluhopis?", ["Kupuješ vlastnický podíl", "Půjčuješ emitentovi peníze", "Zaručuješ, že firma nemůže selhat"], 1, "Dluhopis je pohledávka z půjčky. Emitent slibuje platby, ale může selhat.", "Akcie znamená vlastnictví. Dluhopis znamená půjčku a ani slíbené platby nejsou bez rizika emitenta.")),
  mastery("Ověření znalostí · úrokové sazby", question("mastery-rates", "Nové srovnatelné dluhopisy nabízejí 5 %, starší dluhopis s pevným kupónem jen 3 %. Co se obvykle stane?", ["Starší dluhopis bude při stejné ceně atraktivnější", "Tržní cena staršího dluhopisu bude mít tendenci klesnout", "Emitent musí okamžitě zvýšit kupón"], 1, "Nižší pevná platba je méně konkurenceschopná, proto má tržní cena staršího dluhopisu tendenci klesnout.", "Stávající kupón je pevný. Novým alternativám se běžně přizpůsobuje tržní cena, ne slíbený kupón.")),
  { title: "Rozpoznej úkol každého aktiva", blocks: [bridge("Portfolio Lab odděluje dostupnou hotovost od investovaných pozic. Také dluhopisy mají tržní cenu, která se může měnit."), summary("Hotovost nabízí likviditu a nominální stabilitu, ale čelí inflaci. Dluhopis je půjčka s jistinou, kupónem a splatností; jeho hodnotu ovlivňuje riziko emitenta i změny tržních sazeb.")] },
];

const markets: AuthoredStep[] = [
  { title: "Obchod potřebuje dvě strany", blocks: [question("opening", "Když na burze kupuješ již vydanou akcii, kdo ti ji obvykle prodává?", ["Přímo firma", "Jiný účastník trhu ochotný prodat", "Burza ze svých zásob"], 1, "Běžné burzovní obchody probíhají na sekundárním trhu mezi jeho účastníky. Burza jim pomáhá se potkat.", "Firma vydává cenné papíry na primárním trhu. Při běžném obchodování si již vydaný cenný papír předávají investoři.")] },
  { title: "Čti obě strany kotace", blocks: [figure("quote", "market-quote-explorer", "Bid, ask a spread", "Bid je 99,80 Kč a ask 100,20 Kč. Vyber okamžitý nákup nebo prodej a sleduj, která strana kotace rozhoduje.")] },
  { title: "Směr obchodu určuje cenu", blocks: [question("buy-side", "Bid je 99,80 Kč a ask 100,20 Kč. Která cena je důležitá při okamžitém nákupu?", ["Bid · 99,80 Kč", "Ask · 100,20 Kč", "Střed · 100,00 Kč"], 1, "Okamžitý kupující se zpravidla potká s aktuální nabídkou prodávajících na ceně ask.", "Ne tak docela. Bid je poptávka kupujících. Při okamžitém nákupu se díváš na ask, protože za něj prodávající aktivum nabízejí.")] },
  { title: "Spočítej rozdíl", blocks: [numeric("spread-practice", "Bid je 99,80 Kč a ask 100,20 Kč. Jak velký je spread?", 0.4, "Kč", "100,20 Kč − 99,80 Kč = 0,40 Kč.", "Odečti bid od ask: 100,20 − 99,80.")] },
  { title: "Zobrazená kotace se může změnit", blocks: [concept("market-order", "Okamžitě neznamená za přesnou cenu", "Tržní pokyn upřednostňuje provedení. Kotace se může změnit a větší pokyn se může provést za více cen. Limitní pokyn stanoví cenovou podmínku, ale nemusí se provést vůbec.")] },
  mastery("Ověření znalostí · okamžitý prodej", question("mastery-sell", "Která strana kotace je obvykle důležitá při okamžitém prodeji?", ["Ask", "Bid", "Závěrečná cena předchozího dne"], 1, "Okamžitý prodávající obvykle přijme nejvyšší aktuální nabídku kupujících na ceně bid.", "Ask ukazuje nabídky prodávajících. Při okamžitém prodeji obvykle přijímáš aktuální poptávku na ceně bid.")),
  mastery("Ověření znalostí · volba pokynu", question("mastery-order", "Nechceš zaplatit více než 100 Kč. Který pokyn tuto podmínku vyjadřuje?", ["Tržní nákupní pokyn", "Limitní nákupní pokyn na 100 Kč", "Okamžitý prodej"], 1, "Limitní nákup stanoví nejvyšší přijatelnou cenu, ale nezaručuje provedení.", "Tržní pokyn upřednostňuje provedení a přesnou nejvyšší cenu neslibuje. Cenovou podmínku vyjadřuje limitní pokyn.")),
  { title: "Věz, co kotace slibuje — a co ne", blocks: [bridge("Portfolio Lab před potvrzením ukáže tržní cenu. Skutečné provedení se od kotace může lišit; vzdělávací Lab určuje cenu na serveru podle uvedeného zdroje dat."), summary("Trh propojuje kupující a prodávající. Okamžitý kupující se potkává s ask, okamžitý prodávající s bid. Spread je ask − bid a zobrazená kotace není zárukou ceny provedení.")] },
];

const returnsAndCompounding: AuthoredStep[] = [
  { title: "Nejdřív odhadni, potom počítej", blocks: [question("opening", "Hodnota začne na 100, vzroste o 20 % a potom klesne o 20 %. Kde skončí?", ["100", "96", "104", "80"], 1, "100 × 1,20 × 0,80 = 96. Celkový výnos je −4 %.", "Pokles o 20 % se počítá ze 120, ne z původních 100. Procentní změny se násobí a každá pracuje s novým základem.")] },
  { title: "Převeď změnu na relativní výnos", blocks: [{ id: "return-formula", type: "formula", expression: "R = (V1 - V0) / V0", latex: "R = \\frac{V_1 - V_0}{V_0}", variables: [{ symbol: "V₀", description: "Počáteční hodnota" }, { symbol: "V₁", description: "Konečná hodnota" }, { symbol: "R", description: "Jednoduchý výnos jako desetinné číslo" }] }, { id: "growth-factor", type: "formula", expression: "growth factor = 1 + R", latex: "g = 1 + R", variables: [{ symbol: "R", description: "Výnos za období" }, { symbol: "g", description: "Růstový faktor násobící počáteční hodnotu" }] }] },
  { title: "Spočítej jedno období", blocks: [numeric("positive-return", "Hodnota vzrostla ze 100 na 110. Jaký je výnos v procentech?", 10, "%", "(110 − 100) ÷ 100 = 0,10 = 10 %.", "Zisk 10 vyděl počáteční hodnotou 100 a výsledek 0,10 převeď na 10 %.")] },
  { title: "Násob přes měnící se základ", blocks: [figure("compounding", "compounding-explorer", "Složené zhodnocení", "Začni na 100 a použij +20 % a potom −20 %. Aritmetický součet je 0 %, ale součin růstových faktorů dává 96 a celkový výnos −4 %.")] },
  mastery("Ověření znalostí · výpočet ztráty", numeric("mastery-negative", "Hodnota klesla ze 100 na 80. Jaký je výnos v procentech?", -20, "%", "(80 − 100) ÷ 100 = −0,20 = −20 %.", "Změna je −20. Vyděl ji počáteční hodnotou 100 a převeď na procenta.")),
  mastery("Ověření znalostí · složení dvou změn", numeric("mastery-compound", "Hodnota 100 vzroste o 20 % a potom klesne o 20 %. Jaká je konečná hodnota?", 96, "", "100 × 1,20 × 0,80 = 96. Celkový výnos je −4 %.", "Použij postupně oba růstové faktory: nejdřív 1,20 a potom 0,80.")),
  { title: "Přenášej nový základ dál", blocks: [bridge("Na tomhle výpočtu stojí procenta výnosu a grafy růstu napříč investi."), summary("Jednoduchý výnos měří relativní změnu. Výnos R odpovídá růstovému faktoru 1 + R. Mezi obdobími se růstové faktory násobí, proto se stejně velký růst a pokles nevyruší.")] },
];

const portfolio: AuthoredStep[] = [
  { title: "Portfolio je celý soubor majetku", blocks: [question("opening", "Co patří do celkové hodnoty portfolia?", ["Jen investované pozice", "Jen hotovost", "Hotovost a aktuální hodnota všech pozic"], 2, "Hodnota portfolia spojuje dostupnou hotovost a hodnotu všech pozic.", "Do portfolia patří také hotovost. Celková hodnota je hotovost plus aktuální tržní hodnota držených pozic.")] },
  { title: "Váhy popisují vliv", blocks: [{ id: "weight-formula", type: "formula", expression: "weight_i = positionValue_i / portfolioValue", latex: "w_i = \\frac{V_i}{V_p}", variables: [{ symbol: "Vᵢ", description: "Hodnota jedné pozice" }, { symbol: "Vₚ", description: "Celková hodnota portfolia včetně hotovosti" }, { symbol: "wᵢ", description: "Váha pozice jako desetinné číslo" }] }, { id: "weight-example", type: "workedExample", title: "Portfolio v hodnotě 5 000 Kč", steps: [{ label: "ETF", value: "2 000 Kč · 40 %" }, { label: "Akcie", value: "1 000 Kč · 20 %" }, { label: "Hotovost", value: "2 000 Kč · 40 %" }], conclusion: "Hodnoty dávají dohromady 5 000 Kč a váhy 100 %. Hotovost má váhu, protože je součástí hodnoty portfolia." }] },
  { title: "Spočítej jednu váhu", blocks: [numeric("weight-practice", "ETF má v portfoliu 5 000 Kč hodnotu 2 000 Kč. Jakou má váhu v procentech?", 40, "%", "2 000 ÷ 5 000 = 0,40 = 40 %.", "Vyděl hodnotu pozice 2 000 Kč celkovou hodnotou portfolia 5 000 Kč a výsledek převeď na procenta.")] },
  { title: "Propoj váhu s příspěvkem k výnosu", blocks: [paragraph("contribution", "Výnos pozice ovlivňuje portfolio úměrně její váze. Pro jednoduchou představu za jedno období vynásob váhu výnosem aktiva."), numeric("contribution-practice", "Pozice s vahou 40 % dosáhne výnosu +5 %. Kolika procentními body přibližně přispěje k výsledku portfolia?", 2, "p. b.", "40 % × 5 % = 2 procentní body příspěvku.", "Použij desetinnou váhu: 0,40 × 5 % = 2 procentní body.")] },
  { title: "Zkoumej koncentraci, ne počet řádků", blocks: [figure("diversification", "diversification-impact", "Když jedna pozice klesne", "Porovnej portfolio soustředěné do firmy A s portfoliem rozděleným mezi čtyři firmy. Potom sleduj, co se stane, když všechny čtyři klesnou společně.")] },
  mastery("Ověření znalostí · váha akcie", numeric("mastery-stock-weight", "Akciová pozice má v portfoliu 5 000 Kč hodnotu 1 000 Kč. Jakou má váhu v procentech?", 20, "%", "1 000 ÷ 5 000 = 0,20 = 20 %.", "Vyděl hodnotu akciové pozice 1 000 Kč celkovou hodnotou portfolia 5 000 Kč.")),
  mastery("Ověření znalostí · diverzifikace", question("mastery-diversification", "Portfolio obsahuje 20 technologických akcií s podobnými riziky a jedna pozice tvoří 45 %. Stačí počet řádků k závěru, že je dobře diverzifikované?", ["Ano, více než deset pozic vždy znamená diverzifikaci", "Ne, stále záleží na vahách a společných rizicích", "Ano, protože jde o různé právní společnosti"], 1, "Diverzifikace závisí na tom, co vlastníš, jak velké jsou jednotlivé pozice a zda nesou podobná rizika.", "Dlouhý seznam může být stále koncentrovaný podle vah, sektoru, země nebo společných zdrojů rizika.")),
  { title: "Teď umíš číst portfolio", blocks: [bridge("Váha určuje, jak silně konkrétní pozice ovlivňuje celé portfolio. Portfolio Lab ji počítá z hodnot pozic i hotovosti."), summary("Hodnota portfolia je hotovost plus hodnota pozic. Váha pozice je její hodnota vydělená celkovou hodnotou portfolia. Větší váhy mají větší vliv a skutečná diverzifikace závisí na expozicích a vahách, ne jen na počtu řádků.")] },
];

const flows = [whyInvest, stocks, etfs, bondsAndCash, markets, returnsAndCompounding, portfolio];
export const foundationsContent: AuthoredLesson[] = flows.map((steps, index) => {
  const definition = foundationsLessons[index];
  return { id: definition.id, moduleSlug: "investing-foundations", slug: definition.slug, title: definition.title, eyebrow: "Základy investování", position: index + 1, estimatedMinutes: definition.estimatedMinutes, sections: steps.map((step, position) => ({ id: String(position), label: step.title })), blocks: steps.flatMap((step) => step.blocks) };
});

/** Author each block once; the shared guided runner consumes these step definitions. */
export const foundationsSteps: Record<string, { title: string; kind?: StepKind; blocks: string[] }[]> = Object.fromEntries(flows.map((steps, index) => [foundationsLessons[index].id, steps.map((step) => ({ title: step.title, kind: step.kind, blocks: step.blocks.map((block) => block.id) }))]));
