import type { AuthoredLesson, LessonBlock } from "../types";
import { foundationsLessons } from "./manifest";

type AuthoredStep = { title: string; blocks: LessonBlock[] };
const paragraph = (id: string, content: string): LessonBlock => ({ id, type: "paragraph", content });
const concept = (id: string, title: string, content: string): LessonBlock => ({ id, type: "conceptCallout", title, content });
const question = (id: string, prompt: string, options: string[], correct: number, explanation: string): LessonBlock => ({ id, type: "multipleChoiceQuestion", prompt, options: options.map((label, index) => ({ id: String(index), label })), correctOptionId: String(correct), correctExplanation: explanation, incorrectExplanation: explanation });
const figure = (id: string, kind: Extract<LessonBlock, { type: "interactiveFigure" }>["figure"], title: string, description: string): LessonBlock => ({ id, type: "interactiveFigure", figure: kind, title, description });
const takeaway = (content: string): LessonBlock => ({ id: "takeaway", type: "takeaway", title: "Take this with you", content });

const whyInvest: AuthoredStep[] = [
  { title: "Same money, different purchasing power", blocks: [question("opening", "What happens to €100 kept as cash if prices rise over time?", ["It buys more than before", "It buys less, even though it is still €100", "Its purchasing power cannot change"], 1, "The amount is still €100. Purchasing power describes what that money can buy. When prices rise, an unchanged amount buys less.")] },
  { title: "Two tools for different needs", blocks: [paragraph("tools", "Saving means setting money aside, often in cash or a deposit account. Cash is useful when you need ready access to money: that is liquidity. Short-term spending and unexpected expenses can make access and stability especially valuable."), concept("investing", "Why investing exists", "Investing commits money to assets in the hope of future income or growth. It means accepting uncertainty, including possible losses. Saving and investing serve different purposes; this lesson is about understanding the tools, not telling you to invest.")] },
  { title: "Think in baskets, not just euros", blocks: [{ id: "purchasing-power", type: "workedExample", title: "The same shopping basket", steps: [{ label: "Basket before a price rise", value: "€100" }, { label: "Basket after a 10% price rise", value: "€110" }], conclusion: "Your unchanged €100 now falls €10 short of the same basket. Inflation describes a broad rise in prices, not just one item becoming expensive. Savings interest can offset some or all of that change; the result depends on both interest and prices." }] },
  { title: "Where could growth come from?", blocks: [paragraph("assets", "A business may use money to make products, improve services, and earn profits. Owners may benefit if the business becomes more valuable or distributes some of its earnings. Other investments may pay income, such as interest on a loan."), concept("not-automatic", "An opportunity, not a promise", "Projects can fail, profits can shrink, and buyers can value an asset differently. An asset can lose value even if its story sounds promising.")] },
  { title: "Time gives growth room to build", blocks: [{ id: "time-example", type: "workedExample", title: "Growth on earlier growth", steps: [{ label: "€100 after a hypothetical 5% year", value: "€105" }, { label: "Another hypothetical 5% year", value: "€110.25" }], conclusion: "In the second year, 5% applies to €105, so the gain is €5.25. This is compounding: changes build on the value already there. More time can amplify growth, but it does not remove losses or guarantee a positive outcome." }] },
  { title: "Risk enters the picture", blocks: [concept("risk", "Expected is not certain", "Higher expected return generally involves taking more risk. Expected return is a view about possible future outcomes, not a payment someone owes you. Taking more risk does not ensure a higher realized return."), paragraph("loss", "Investment values can fall significantly, and you can lose money. Time may allow growth to accumulate, but needing to sell during a fall can matter. That is one reason liquidity and time horizon belong in the same conversation.")] },
  { title: "Change the assumptions", blocks: [figure("growth", "growth-comparison", "Growth comparison", "Before changing the time from 10 to 20 years, predict whether the gain will simply double. Then try it. You can also enter a negative rate to see losses compound.")] },
  { title: "Match the tool to the idea", blocks: [question("check", "Which statement best connects saving, investing, and risk?", ["Cash is useless because prices can rise", "Investing guarantees more purchasing power", "Cash can serve near-term needs; investing offers uncertain future growth"], 2, "Cash can be useful for liquidity and short-term needs. Investing accepts uncertainty in pursuit of income or growth. Neither a smooth illustration nor a long time period guarantees profit.")] },
  { title: "A reason to understand both", blocks: [takeaway("Money has an amount and a purchasing power. Saving can keep money accessible; investing accepts risk for possible future income or growth. Compounding makes time matter, while inflation and uncertain outcomes make the assumptions matter too.")] },
];

const stocks: AuthoredStep[] = [
  { title: "Imagine a business split into pieces", blocks: [paragraph("imagine", "Imagine a small business divided into 1,000,000 equal shares of one class. Each share represents a small ownership interest in the company. Buying shares connects your financial outcome to the business and to the price other investors will pay."), question("share", "What does one share represent?", ["A loan the company must repay", "An ownership interest in the company", "The right to run the company every day"], 1, "A share is ownership, rather than a promise of repayment. Shareholders may have voting rights, but managers and directors run the company; a small shareholding does not give control over daily operations.")] },
  { title: "How much of the business?", blocks: [figure("ownership", "ownership-explorer", "Ownership explorer", "Predict your percentage if you own 100 of 1,000,000 shares. It is 0.01%: 100 ÷ 1,000,000 = 0.0001 of the company, then multiply by 100 for a percentage. Change the inputs to see what changes your slice.")] },
  { title: "A price is attached to each piece", blocks: [concept("price", "Price and ownership answer different questions", "Your ownership fraction depends on how many shares you own relative to shares outstanding. The current share price tells you what one share trades for. A €5 share does not necessarily represent a cheaper company than a €50 share: the number of shares also matters.")] },
  { title: "Put a value on all the shares", blocks: [figure("cap", "market-cap-explorer", "Market capitalization", "Market capitalization is share price × shares outstanding. It is the market value of a company’s equity based on the current share price. It is not revenue, profit, cash, or enterprise value (a broader measure that also accounts for debt and cash). This example uses one share class.")] },
  { title: "Why can the price move?", blocks: [paragraph("movement", "Buyers and sellers react to expectations about future earnings, business risks, interest rates, and news. Those expectations can change even before reported profits do. Prices can rise or fall significantly."), concept("value", "A market estimate, not a fact about the future", "Market cap changes with the market price. It is not a definitive measure of what a business is intrinsically worth, and it does not mean the company has that amount sitting in a bank account.")] },
  { title: "Owners may receive dividends", blocks: [paragraph("dividend", "A dividend is a distribution a company makes to shareholders, often in cash. Some companies pay them; others reinvest earnings. Dividends can be reduced or stopped and are not guaranteed."), concept("not-free", "A distribution is not free extra value", "Paying a cash dividend moves money out of the company to shareholders. All else equal, the share price adjusts downward by the dividend amount when new buyers no longer receive that payment. Total outcomes include both price changes and distributions.")] },
  { title: "Practice the ownership fraction", blocks: [{ id: "practice", type: "numericQuestion", prompt: "You own 100 of a company’s 1,000,000 equal shares. What percentage do you own?", answer: 0.01, tolerance: 0.000001, unit: "%", correctExplanation: "100 ÷ 1,000,000 × 100 = 0.01%. A fraction of 0.0001 is a percentage of 0.01%.", incorrectExplanation: "Divide your 100 shares by all 1,000,000 shares, then multiply by 100. Your fraction is 0.0001; your percentage is 0.01%." }] },
  { title: "Separate company size from share price", blocks: [question("cap-check", "A company has 1,000,000 shares outstanding at €50 each. What does its €50,000,000 market cap measure?", ["Its annual revenue", "Its cash balance", "The current market value of its equity"], 2, "€50 × 1,000,000 = €50,000,000. That prices all outstanding shares at the current share price. It does not tell us revenue, profit, or cash.")] },
  { title: "Ownership is not daily control", blocks: [concept("misconceptions", "A small piece, with real uncertainty", "Owning 100 shares does not mean you can direct employees or withdraw company money. You participate economically through the value of your holding and any distributions. A profitable company’s shares can still fall in price; ownership does not guarantee a gain.")] },
  { title: "Connect the three numbers", blocks: [takeaway("Shares connect you to company ownership. Owned shares ÷ shares outstanding tells you your fraction; share price × shares outstanding gives market cap. Prices and dividends can change, and neither ownership nor company profits guarantee your investment outcome.")] },
];

const etfs: AuthoredStep[] = [
  { title: "Hundreds of companies, one purchase?", blocks: [question("opening", "You want exposure to hundreds of companies. Do you need to buy every stock individually?", ["Yes, each company always needs a separate purchase", "No, a diversified fund can hold them for its investors"], 1, "A fund pools money and holds investments. A diversified fund can provide exposure to many companies through one holding, which can simplify buying and maintaining individual positions.")] },
  { title: "Why spread exposure?", blocks: [paragraph("diversification", "If you own one company, its problems can dominate your outcome. Spreading exposure across different businesses can reduce dependence on any one company. Buying and maintaining hundreds of positions individually can involve time, trades, and rebalancing."), concept("shared-risk", "Different companies can still fall together", "Diversification reduces some risks, particularly dependence on individual holdings. It cannot remove broad market risk or guarantee against losses. A narrowly focused fund may provide little diversification.")] },
  { title: "An index is a measuring tool", blocks: [paragraph("index", "An index uses a defined methodology to select and measure a group of assets. It describes how that group performs. The S&P 500, for example, measures a selection of roughly 500 large U.S. companies; it is not every company or the entire economy."), figure("map", "index-etf-visual", "From measurement to investment", "Think of the index as the measuring rule and an index-tracking ETF as a fund trying to follow it. This is one ETF strategy, not the definition of every ETF.")] },
  { title: "Which can you buy?", blocks: [question("buy", "Which can you directly buy shares of on an exchange?", ["An index itself", "An ETF"], 1, "You buy shares of an ETF, an investable fund. An index itself is a measurement. You can seek exposure to its performance through a product such as an index-tracking fund.")] },
  { title: "A fund can follow different strategies", blocks: [paragraph("fund", "An exchange-traded fund (ETF) pools investments and has shares that trade on an exchange. An investor owns shares of the fund, which provide exposure to its holdings, rather than directly owning each underlying company’s shares."), question("strategy", "Does an ETF always track an index?", ["Yes, ETF is another name for an index", "No, an ETF can follow an index or another strategy"], 1, "Some ETFs seek to track an index. Others are actively managed or follow other strategies. ETF describes the investment vehicle; index describes a measurement.")] },
  { title: "A basket still carries risk", blocks: [question("risk", "Does diversification eliminate risk?", ["Yes, enough holdings guarantee no loss", "No, a diversified fund can still lose value"], 1, "Holdings can fall together, and risks depend on the assets and strategy. An ETF is not automatically diversified or safe simply because it is a fund.")] },
  { title: "Keep the distinction clear", blocks: [question("measurement", "What is an index primarily?", ["A measurement of an asset group under a defined methodology", "A fund you can always buy directly", "A guarantee of diversified returns"], 0, "An index measures a group according to a methodology. A fund may use that index as a target, but the measurement and the investable product are separate things.")] },
  { title: "Look inside the fund", blocks: [paragraph("assets", "ETFs can provide exposure to stocks, bonds, commodities, or other assets. The structure and strategy determine whether assets are held directly or exposure comes through instruments such as derivatives. Different holdings and strategies bring different risks."), concept("fees", "Fees affect what investors keep", "Funds charge fees and incur costs, which reduce investor returns. An index-tracking ETF may differ from its index because of fees, trading costs, and imperfect tracking. The same index does not make every fund identical.")] },
  { title: "Try explaining it to someone else", blocks: [concept("explain", "The measurement and the vehicle", "Imagine someone says, ‘I bought the index, so I cannot lose money.’ Pause and correct both ideas in your own words: they bought an investment product seeking index exposure, and that product can lose value.")] },
  { title: "One distinction opens the next door", blocks: [takeaway("An index measures. An ETF is a fund you can buy shares of; it may track an index or follow another strategy. Funds can make broad exposure convenient, but diversification, risk, and fees depend on what the fund actually does.")] },
];

const bondsAndCash: AuthoredStep[] = [
  { title: "Owning and lending are different roles", blocks: [question("opening", "What is the main difference between buying a stock and buying a bond?", ["A stock is ownership; a bond is a loan", "A stock is a loan; a bond is ownership", "They always give the same kind of claim"], 0, "A stock represents ownership in a company. A bond represents lending money to an issuer. Both can be investments, but the relationship is different.")] },
  { title: "Cash keeps money ready", blocks: [paragraph("cash", "Cash is immediately available money: the balance you can use for spending, a surprise expense, or a near-term goal. This ready access is called liquidity. In nominal terms, cash usually does not swing in value like a traded investment can."), concept("purchasing-power", "The amount and what it can buy", "€1,000 remains €1,000 in nominal amount. Over time, inflation can reduce what that same amount buys if prices rise. That does not make cash bad: access, stability, and short-term needs can be valuable."), question("cash-check", "Which asset is generally most directly designed for immediate liquidity?", ["Cash", "A stock", "A bond"], 0, "Cash is designed to be ready for use. Stocks and bonds may be sold, but their market price and ease of sale can differ from the amount originally invested.")] },
  { title: "Every loan has two sides", blocks: [paragraph("borrower-lender", "A borrower receives money now and promises to repay under agreed terms. A lender provides the money and expects those payments. Governments and companies may borrow to fund public services, projects, operations, or expansion rather than relying only on money they already have."), concept("issuer", "The issuer is the borrower", "When a government or company creates a bond, it is the issuer. Buying that bond means you are lending to that issuer; you do not become an owner of it.")] },
  { title: "A bond packages a loan", blocks: [paragraph("bond", "A bond is a financial instrument that represents a loan. In a typical fixed-rate bond, the issuer promises interest payments and repayment of the principal at a stated date, called maturity. The promise depends on the issuer being able and willing to pay."), question("bond-check", "When you buy a corporate bond, what are you primarily doing?", ["Buying part of the company", "Lending money to the company", "Depositing money into its bank account"], 1, "You are lending to the company that issued the bond. Stockholders own part of a company; bondholders have a lending claim instead.")] },
  { title: "Three terms describe the promise", blocks: [{ id: "terms", type: "workedExample", title: "A €1,000 five-year bond", introduction: "Imagine a company issues a bond with a 5% annual coupon. These words describe its promised cash flows, not its market price.", steps: [{ label: "Principal (or face value)", value: "€1,000 lent" }, { label: "Interest (or coupon)", value: "5% of principal each year" }, { label: "Maturity", value: "Principal due in 5 years" }], conclusion: "The principal is the original loan amount. The coupon is the stated interest payment. Maturity is when the principal is typically due back—assuming the issuer makes the promised payments." }, { id: "coupon-practice", type: "numericQuestion", prompt: "A €1,000 bond has a 5% annual coupon. What is its annual coupon payment?", answer: 50, tolerance: 0.000001, unit: "€", correctExplanation: "5% of €1,000 is €50. This is the annual coupon payment, not a statement about the bond’s total investment return.", incorrectExplanation: "Multiply the €1,000 principal by 5%: €1,000 × 0.05 = €50. Coupon payments and total return are different ideas." }] },
  { title: "Follow the promised cash flows", blocks: [figure("cashflows", "bond-cashflow-explorer", "Bond cash-flow illustration", "Use the default €1,000 principal, 5% annual coupon, and 5 years to see the stated payments. This is a simplified cash-flow illustration, not a yield or investment-return calculation.")] },
  { title: "A bond can trade at a new price", blocks: [paragraph("rates", "After a bond is issued, investors may trade it with each other. Imagine an existing bond pays a fixed 3% coupon while newly issued similar bonds offer 5%. At the same price, the older bond is usually less attractive because its payments are lower."), concept("rate-direction", "A useful direction, not a complete pricing rule", "All else equal, when market interest rates rise, existing fixed-rate bond prices tend to fall. When market rates fall, their prices tend to rise. A bond’s yield is another way markets describe its payments relative to its price, so it can change as the market price changes. Other factors—such as the issuer’s financial health and time to maturity—also matter."), question("rate-check", "If new similar bonds offer much higher interest rates, what generally happens to an older low-rate bond at the same price?", ["It becomes less attractive", "It automatically becomes risk-free", "Its coupon payment rises to match"], 0, "The older bond’s fixed coupon does not reset just because new bonds offer more. Its market price can change, and market value is not always the original issue price.")] },
  { title: "A promise is not the same as certainty", blocks: [paragraph("credit", "An issuer may struggle or fail to make promised payments. This credit or default risk differs across issuers, including governments and companies."), paragraph("interest-rate", "If you sell before maturity, interest-rate changes can affect the market price you receive. Fixed payments can also lose purchasing power when inflation rises."), paragraph("liquidity", "Some bonds can be harder to sell quickly at a desired price. Government bonds can have different risk profiles from corporate bonds, but no bond is automatically risk-free in every sense."), question("government-risk", "Are government bonds automatically risk-free in every sense?", ["Yes, a government bond cannot have any risk", "No, different risks can still matter"], 1, "No. The issuer, market-price changes, inflation, and liquidity can matter in different ways. Risk is not one single thing.")] },
  { title: "Choose the relationship, then the purpose", blocks: [figure("comparison", "asset-comparison", "Cash, bonds, and stocks", "Select each asset to compare the relationship and its common purpose. The labels are broad starting points, not a recommendation for any one person.")] },
  { title: "Three mental models to keep", blocks: [takeaway("Cash is immediately available money for liquidity and near-term needs. A bond means, “I lend money to someone,” with promised interest and principal repayment that carry real risks. A stock means, “I own part of something.” None is universally better; the useful choice depends on your goal, time horizon, and the risks you can take.")] },
];

const markets: AuthoredStep[] = [
  { title: "A market needs a meeting point", blocks: [paragraph("marketplace", "A financial market is a marketplace that connects people who want to buy with people who want to sell. An exchange is one organized place where this can happen. You want one share; another participant offers to sell one for €100 while a buyer offers €99."), question("opening", "With a buyer at €99 and a seller at €100, is there a trade yet?", ["Yes, because both participants are in the same market", "No, their prices do not meet yet", "Yes, the company fills the difference"], 1, "There is not a trade yet: the buyer is willing to pay €99 and the seller wants €100. A trade can happen when a buyer and seller agree on a price. The company does not normally fill that gap in an ordinary exchange trade.")] },
  { title: "Bid and ask name each side", blocks: [concept("quotes", "Two current interests", "The bid is the highest current buying interest. The ask is the lowest current selling interest. With a €99 bid and €100 ask, an immediate buyer typically pays attention to the ask; an immediate seller typically pays attention to the bid."), question("buy-now", "Bid = €49 and ask = €50. If you want to buy immediately, which quote is most relevant?", ["The €49 bid", "The €50 ask", "The average of both quotes"], 1, "An immediate buyer typically interacts with the ask, the current selling interest. Quotes can change, so this is execution intuition rather than a guaranteed final price.")] },
  { title: "Choose what you want the order to express", blocks: [figure("quote-explorer", "market-quote-explorer", "Bid, ask, and order choices", "Try buying now, selling now, or waiting with a limit. Each choice expresses a different priority; this small example is not a live quote or a guarantee of execution.")] },
  { title: "The gap is the spread", blocks: [{ id: "spread-example", type: "workedExample", title: "Read the difference between the quotes", steps: [{ label: "Bid", value: "€49.80" }, { label: "Ask", value: "€50.00" }, { label: "Bid-ask spread", value: "€0.20" }], conclusion: "The spread is ask − bid. A tighter spread often appears in more easily traded conditions, but it is only one clue about liquidity—not a complete measure and not a measure of safety." }, question("sell-now", "If you want to sell immediately, which side of the quote is generally most relevant?", ["The ask", "The bid", "The company’s issue price"], 1, "An immediate seller typically interacts with the bid, the current buying interest. The ask is the selling interest an immediate buyer typically meets.")] },
  { title: "Execution and price constraints differ", blocks: [paragraph("order-types", "A market order prioritizes trying to execute promptly. The price can move between the quote you see and execution, sometimes called slippage. A limit order sets a price condition: for example, a limit buy at €95 can execute only at €95 or better."), concept("not-advice", "Two instructions, neither universally better", "A market order expresses “I prioritize execution.” A limit order expresses “I care about this price.” A limit order may never execute, and a market order does not guarantee an exact displayed price."), question("limit-check", "Current ask = €100. You place a limit buy at €95. Is execution guaranteed?", ["Yes, because a limit order always completes", "No, the market may never reach €95 or offer enough shares there"], 1, "No. The limit gives a price constraint, not a promise that another participant will trade with you at that price.")] },
  { title: "Most everyday trades are between investors", blocks: [paragraph("primary-secondary", "In a primary market, a company issues new securities and the money raised goes to the issuer. In a secondary market, people trade securities that already exist with one another. Most ordinary exchange purchases by retail investors are secondary-market transactions."), question("secondary-check", "When you buy an existing public share on an exchange, who do you normally buy it from?", ["The company directly", "Another market participant who is selling", "The exchange itself"], 1, "Usually another participant is selling the existing share. An exchange helps match and process the trade; it is not normally the owner of the share.")] },
  { title: "Prices are discovered through trades", blocks: [paragraph("discovery", "A market price emerges from transactions and the interests of buyers and sellers. A company does not simply announce, “Our share is worth €73.42 today,” and make that continuously changing market price happen."), question("price-discovery", "Many buyers become willing to pay more while available sellers remain limited. What pressure would this usually place on the market price?", ["Upward pressure", "Downward pressure", "No pressure because prices are set by the company"], 0, "More eager buying relative to available selling generally puts upward pressure on prices. The company does not normally set its continuously changing exchange price directly.")] },
  { title: "Liquidity is ease, not safety", blocks: [figure("liquidity", "liquidity-comparison", "Compare trading conditions", "Compare a highly traded large-company stock with a thinly traded obscure security. Liquidity is about how easily trading can generally happen near the prevailing price, not whether the investment is safe.")] },
  { title: "Many forces can move a price", blocks: [paragraph("movement", "New information, earnings expectations, interest rates, risk perception, the supply and demand for a security, and broader market conditions can all affect buying and selling interest. A price change does not always have one clear cause."), question("liquidity-safe", "Does high liquidity mean an investment cannot lose value?", ["Yes, easy trading makes the value safe", "No, liquidity and the risk of losing value are different ideas"], 1, "No. Liquidity concerns ease of trading; even a very liquid investment can fall in value.")] },
  { title: "Markets match views, not certainties", blocks: [takeaway("Markets connect buyers and sellers. Prices emerge through trading, while liquidity affects how easily trading can happen. A market order says “I prioritize execution”; a limit order says “I care about this price.” Neither instruction removes uncertainty.")] },
];

const riskReward: AuthoredStep[] = [
  { title: "Different outcomes can be equally possible", blocks: [question("opening", "Option A guarantees €100 in one year. Option B has a 50% chance of €80 and a 50% chance of €140. Are these outcomes equally certain?", ["Yes, because both mention money in one year", "No, Option B has uncertain outcomes"], 1, "No. Option B can end in different places, including below €100. Investing outcomes are generally not known in advance; uncertainty is a central part of risk.")] },
  { title: "Expected is not realized", blocks: [paragraph("expected-realized", "Expected return is an estimate or anticipation across possible outcomes. Realized return is what actually happened. An investment can have a positive expected return and still lose value in a particular year."), question("realized-check", "What is realized return?", ["What actually occurred over the period", "The return someone hoped for", "A return that is guaranteed"], 0, "Realized return is the outcome that actually occurred. Expectations can be useful estimates, but they are not promises and are not precisely knowable in advance.")] },
  { title: "More potential reward can mean more uncertainty", blocks: [concept("tradeoff", "Expected does not mean guaranteed", "Investors generally demand a higher expected return for taking more uncertainty or risk. That does not mean higher risk guarantees a higher realized return; the result can still be poor."), question("higher-risk", "Does higher risk guarantee a higher return?", ["Yes, more risk always pays more", "No, a higher expected return can still be followed by a poor realized return"], 1, "No. Risk may be associated with a higher expected return, but realized outcomes can be negative or lower than hoped.")] },
  { title: "Averages can hide the range", blocks: [figure("risk-scenarios", "risk-scenario-explorer", "Possible outcomes can differ", "Compare two simple equal-probability illustrations with the same average listed outcome. Look at the range before treating an average as the whole story.")] },
  { title: "Drawdown describes a fall from a peak", blocks: [figure("drawdown", "drawdown-explorer", "Drawdown from a previous peak", "Start with €10,000 falling to €7,500. Drawdown is the percentage decline from the previous peak, not a prediction of what happens next."), { id: "drawdown-check", type: "numericQuestion", prompt: "A portfolio falls from €10,000 to €8,000. What is the drawdown from that peak?", answer: 20, tolerance: 0.000001, unit: "%", correctExplanation: "The decline is €2,000 from a €10,000 peak: €2,000 ÷ €10,000 = 20%.", incorrectExplanation: "Subtract €8,000 from the €10,000 peak, then divide the €2,000 decline by the €10,000 peak." }] },
  { title: "A loss needs a larger recovery", blocks: [figure("recovery", "recovery-explorer", "Losses and recovery", "Try a −20% change. A 20% gain does not return the value to its starting point because the gain would apply to a smaller base.")] },
  { title: "Risk takes more than one form", blocks: [paragraph("risk-types", "Volatility is one visible form of uncertainty, but not the whole meaning of risk. Business risk is a company performing badly; market risk is a broad market fall; credit risk is a borrower failing to repay; interest-rate changes can affect values; inflation can reduce purchasing power; and liquidity risk can make selling near an expected price difficult."), question("concentration-check", "Which situation is concentration risk?", ["Most of a portfolio depends on one company", "Owning a range of unrelated investments", "Holding cash for a near-term expense"], 0, "Concentration risk means too much of an outcome depends on one holding, company, sector, or similar exposure. It is different from every other kind of risk, and the list here is not exhaustive.")] },
  { title: "Spreading exposure can reduce one dependency", blocks: [figure("diversification", "diversification-preview", "Concentration and diversification", "Compare one company with a spread of investments. Diversification can reduce company-specific concentration risk, but it cannot remove market losses, inflation, or every other risk."), question("diversification-check", "Does diversification eliminate all risk?", ["Yes, a diversified portfolio cannot lose money", "No, it can reduce some risks without removing all risk"], 1, "No. Diversification can reduce dependence on one holding, but broad market falls, inflation, and other risks can remain.")] },
  { title: "The timing of a need matters", blocks: [figure("horizon", "time-horizon-explorer", "Time horizon and uncertainty", "Compare money needed next month with money intended for decades later. This is about when money is needed, not a personalized investment recommendation."), concept("tolerance-capacity", "Comfort and circumstances are different", "Risk tolerance is how comfortable someone feels with uncertainty or loss. Risk capacity is how much financial risk their circumstances can absorb. Someone may feel comfortable with risk yet have low capacity because they need the money soon."), question("horizon-check", "Why can time horizon matter?", ["Money needed soon may have less ability to recover from market losses", "Long-term investing guarantees profit", "Time horizon changes the market’s rules"], 0, "Money needed soon may leave little time to absorb or recover from a fall. More time does not guarantee profit; it changes the practical context for uncertainty.")] },
  { title: "Risk is a question of outcomes and circumstances", blocks: [takeaway("Risk is not volatility alone. Expected return is an estimate; realized return is what happened. Losses, concentration, liquidity, inflation, and time horizon can all matter. Diversification may reduce some risks, while risk tolerance and risk capacity describe different parts of a person’s situation.")] },
];

const flows = [whyInvest, stocks, etfs, bondsAndCash, markets, riskReward];
export const foundationsContent: AuthoredLesson[] = flows.map((steps, index) => {
  const definition = foundationsLessons[index];
  return { id: definition.id, moduleSlug: "investing-foundations", slug: definition.slug, title: definition.title, eyebrow: "Investing Foundations", position: index + 1, estimatedMinutes: definition.estimatedMinutes, sections: steps.map((step, position) => ({ id: String(position), label: step.title })), blocks: steps.flatMap((step) => step.blocks) };
});
/** Author each block once; the shared guided runner consumes these step definitions. */
export const foundationsSteps: Record<string, { title: string; blocks: string[] }[]> = Object.fromEntries(flows.map((steps, index) => [foundationsLessons[index].id, steps.map((step) => ({ title: step.title, blocks: step.blocks.map((block) => block.id) }))]));
